version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: TasksManager
    volumes:
      - /c/Users/sozon/Projects/TasksManager/db_dumps/TasksManager-dump.sql:/docker-entrypoint-initdb.d/TasksManager-dump.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend/taskmanager 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TasksManager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/my-app 
    depends_on:
      - backend
    ports:
      - "3000:3000"
